"""Generate Policy Library / OPA constraints from the engine's knowledge.

This is the "Google-adoptable" artifact: Forseti's policy-library and the
Config Validator / Gatekeeper ecosystem consume OPA (Rego) constraint templates.
We emit a constraint that flags the tag-conditional escalation pattern the
engine detects, so the same rule can run as a *preventive* policy at deploy time
(Terraform validation, CI gate) rather than only as a detective scan.
"""

from __future__ import annotations

from . import knowledge as kb

_REGO_HEADER = """\
# Auto-generated by condor-scan.
# Flags conditional IAM bindings whose condition is keyed on resource tags and
# whose granted role confers escalation-relevant permissions. Such bindings let
# any principal able to attach tags satisfy the condition and self-escalate
# (the "Tag Your Way In" pattern; Mitiga, 2026).
package templates.gcp.GCPIAMTagConditionEscalationConstraintV1

import data.validator.gcp.lib as lib
"""


def _escalation_roles() -> list[str]:
    return sorted(kb.TIER_ZERO_ROLES)


def generate_rego() -> str:
    """Return a Rego constraint-template body for tag-conditional escalation."""
    roles_list = ",\n        ".join(f'"{r}"' for r in _escalation_roles())
    return (
        _REGO_HEADER
        + f"""
escalation_roles := {{
        {roles_list}
}}

# A condition expression is tag-based if it references resource tag matchers.
is_tag_condition(expr) {{
    contains(expr, "resource.matchTag(")
}}
is_tag_condition(expr) {{
    contains(expr, "resource.matchTagId(")
}}

deny[{{"msg": msg, "details": details}}] {{
    binding := input.asset.iam_policy.bindings[_]
    escalation_roles[binding.role]
    expr := binding.condition.expression
    is_tag_condition(expr)

    msg := sprintf(
        "Conditional binding grants escalation role %v under a tag-based condition (%v); tag-attach permission holders can self-escalate.",
        [binding.role, binding.condition.title]
    )
    details := {{
        "resource": input.asset.name,
        "role": binding.role,
        "condition": binding.condition.title,
        "expression": expr,
    }}
}}
"""
    )


def generate_constraint_yaml(name: str = "deny-tag-condition-escalation") -> str:
    """Return the constraint instance YAML that binds the template above."""
    return f"""\
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMTagConditionEscalationConstraintV1
metadata:
  name: {name}
spec:
  severity: high
  match:
    target: ["organizations/**"]
  parameters: {{}}
"""
